### ISSUE TITLE
Invalid filter: add_label_class

### ISSUE THREAD

**Issue by nittolese** [zodman/django-intercoolerjs#1]
Hi,
your repo seems interesting, thanks for sharing! I tried to run your code but I keep obtaining error 500 due to an invalid filter. Could you help me with this issue?
```

Performing system checks...

System check identified no issues (0 silenced).
May 07, 2019 - 17:47:04
Django version 2.2.1, using settings 'example.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Internal Server Error: /
Traceback (most recent call last):
  File "/home/user/.virtualenvs/my_django_environment/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/user/.virtualenvs/my_django_environment/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/user/.virtualenvs/my_django_environment/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/user/django_projects/django-intercoolerjs/example/app/views.py", line 53, in home
    return render(request, "base.html", context)
  File "/home/user/.virtualenvs/my_django_environment/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/user/.virtualenvs/my_django_environment/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/user/.virtualenvs/my_django_environment/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/user/.virtualenvs/my_django_environment/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/user/.virtualenvs/my_django_environment/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/user/.virtualenvs/my_django_environment/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/user/.virtualenvs/my_django_environment/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/user/.virtualenvs/my_django_environment/lib/python3.6/site-packages/django/template/loader_tags.py", line 176, in render
    template = context.template.engine.get_template(template_name)
  File "/home/user/.virtualenvs/my_django_environment/lib/python3.6/site-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/home/user/.virtualenvs/my_django_environment/lib/python3.6/site-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/user/.virtualenvs/my_django_environment/lib/python3.6/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/home/user/.virtualenvs/my_django_environment/lib/python3.6/site-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/user/.virtualenvs/my_django_environment/lib/python3.6/site-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/home/user/.virtualenvs/my_django_environment/lib/python3.6/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/home/user/.virtualenvs/my_django_environment/lib/python3.6/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/home/user/.virtualenvs/my_django_environment/lib/python3.6/site-packages/django/template/defaulttags.py", line 811, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "/home/user/.virtualenvs/my_django_environment/lib/python3.6/site-packages/django/template/base.py", line 449, in parse
    raise self.error(token, e)
  File "/home/user/.virtualenvs/my_django_environment/lib/python3.6/site-packages/django/template/base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/home/user/.virtualenvs/my_django_environment/lib/python3.6/site-packages/django/template/base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "/home/user/.virtualenvs/my_django_environment/lib/python3.6/site-packages/django/template/base.py", line 657, in __init__
    filter_func = parser.find_filter(filter_name)
  File "/home/user/.virtualenvs/my_django_environment/lib/python3.6/site-packages/django/template/base.py", line 569, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'add_label_class'
[07/May/2019 17:47:06] "GET / HTTP/1.1" 500 175650
Not Found: /robots.txt
```

Thank you!

**Comment by zodman** [comment]
you need to install  https://github.com/jazzband/django-widget-tweaks
